library(datashieldclient)
options(verbose=F)
logindata <- read.csv("./tests/logindata.csv")
opals<-datashield.login(logindata, assign=T)
ds.histogram(x='D$LAB_TSC')
ds.histogram(x='D$LAB_TRIG')
ds.histogram(x='D$LAB_HDL')
ds.histogram(x='D$LAB_GLUC_ADJUSTED')
ds.histogram(x='D$PM_BMI_CONTINUOUS')
ds.summary(x='D$DIS_CVA')
ds.summary(x='D$MEDI_LPD')
ds.summary(x='D$DIS_DIAB')
ds.summary(x='D$DIS_AMI')
ds.summary(x='D$GENDER')
ds.summary(x='D$PM_BMI_CATEGORICAL')
datashield.logout(opals)
