library(dsBaseClient)
options(verbose=F)
logindata <- read.csv("./examples/logindata-demo.csv")
opals<-datashield.login(logindata, assign=T)
ds.histogram(x='D$LAB_TSC')
ds.histogram(x='D$LAB_TRIG')
ds.histogram(x='D$LAB_HDL')
ds.histogram(x='D$LAB_GLUC_ADJUSTED')
ds.histogram(x='D$PM_BMI_CONTINUOUS')
ds.summary(x='D$DIS_CVA')
ds.summary(x='D$MEDI_LPD')
ds.summary(x='D$DIS_DIAB')
ds.summary(x='D$DIS_AMI')
ds.summary(x='D$GENDER')
ds.summary(x='D$PM_BMI_CATEGORICAL')
datashield.assign(opals, 'G', as.symbol('D$GENDER'))
ds.summary(x='G')
datashield.assign(opals$server1, 'G2', as.symbol('D$GENDER'))
ds.summary(x='G2', datasources=c(opals$server1))
datashield.symbols(opals)
datashield.commands(opals)
datashield.logout(opals)

logindata <- read.csv("./tests/logindata2.csv")
datashield.status(logindata)

logindata <- read.csv("./tests/logindata3.csv")
library(datashieldclient)
opals<-datashield.login(logindata, assign=T,username="user1",password="password",opts=list(ssl.verifypeer=1,ssl.verifyhost=2))
datashield.logout(opals)
