# DataSHIELD Servers Status

This reports the status of distributed servers.

```{r echo=FALSE, message=FALSE}
library(opal)
logindata <- read.csv("../../../tests/logindata2.csv")
status <- datashield.status(logindata)
colnames(status$package_status)[1] <- "Package"
colnames(status$version_status)[1] <- "Package"
colnames(status$aggregate_status)[1] <- "Function"
colnames(status$assign_status)[1] <- "Function"
```

## Table Access

```{r echo=FALSE,message=FALSE,results='asis'}
opal.as_md_table(status$table_status, col.names=c("Study","URL","Version","Table name","Readable"))
```

## DataSHIELD Package

### Installed Packages

```{r echo=FALSE,message=FALSE,results='asis'}
opal.as_md_table(status$package_status)
```

### Packages Versions

```{r echo=FALSE,message=FALSE,results='asis'}
opal.as_md_table(status$version_status)
```

## DataSHIELD Functions

### Aggregate Functions

```{r echo=FALSE,message=FALSE,results='asis'}
opal.as_md_table(status$aggregate_status)
```

### Assign Functions

```{r echo=FALSE,message=FALSE,results='asis'}
opal.as_md_table(status$assign_status)
```

<style type="text/css">
.navbar {
  display: none;
}

.glyphicon {
  background: none !important;
}
</style>